num1 = input('Enter num1: ')
num2 = input('Enter num2: ')
print('num1: ', num1)
print('num2: ', num2)
print('Sum is:', num1 + num2)
print('Sum is: ', int(num1) + int(num2), '\n')

num3 = int(input('Enter num3: '))
num4 = int(input('Enter num4: '))
print('num3: ', num3)
print('num4: ', num4)
print('Sum is:', num3 + num4)